spring.application.name=AttemptService
spring.data.mongodb.uri=mongodb+srv://njha5901:Jha%402005@attemptservice.xwre4mx.mongodb.net/AttemptService?appName=AttemptService&retryWrites=true&w=majority
spring.data.mongodb.connections-per-host=50
server.port=8090


