spring.application.name=AttemptService
spring.data.mongodb.uri=mongodb+srv://njha5901:Jha%402005@attemptservice.xwre4mx.mongodb.net/AttemptService?appName=AttemptService&retryWrites=true&w=majority
spring.data.mongodb.connections-per-host=50
server.port=8090
# Sirf 5 calls ke baad decision le
resilience4j.circuitbreaker.instances.attemptService.minimumNumberOfCalls=3
# Agar 50% calls fail ho jayein
resilience4j.circuitbreaker.instances.attemptService.failureRateThreshold=50

# 1. Window size chota karo taaki jaldi result dikhe
resilience4j.circuitbreaker.instances.attemptService.slidingWindowSize=3

# 2. Batao ki calls count karni hai
resilience4j.circuitbreaker.instances.attemptService.slidingWindowType=COUNT_BASED

# 3. Wait time badhao (2s bohot kam hai, pata bhi nahi chalega kab OPEN hua kab CLOSED)
resilience4j.circuitbreaker.instances.attemptService.waitDurationInOpenState=30s

# Retry Configuration
resilience4j.retry.instances.attemptRetryService.maxAttempts=3
resilience4j.retry.instances.attemptRetryService.waitDuration=2s
# Ye line sabse zaroori hai Feign errors ko pakadne ke liye
resilience4j.retry.instances.attemptRetryService.retryExceptions=java.lang.Exception

# Circuit Breaker ki priority set karna taaki Retry pehle chale
resilience4j.retry.circuit-breaker-aspect-order=1
resilience4j.circuitbreaker.circuit-breaker-aspect-order=2
