spring.application.name=GateWay
server.port=4571
#routes 1
spring.cloud.gateway.routes[0].id=QuestionService
spring.cloud.gateway.routes[0].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/questions/**
#routes 2
spring.cloud.gateway.routes[1].id=QuizService
spring.cloud.gateway.routes[1].uri=lb://QUIZSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/quizzes/**

#route 3
 spring.cloud.gateway.routes[2].id=UserService
spring.cloud.gateway.routes[2].uri=lb://USERSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/users/**
#route 4
spring.cloud.gateway.routes[3].id=AttemptService
spring.cloud.gateway.routes[3].uri=lb://ATTEMPTSERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/attempts**
