spring.application.name=GateWay
server.port=4571
#routes 1
spring.cloud.gateway.routes[0].id=QuestionService
spring.cloud.gateway.routes[0].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/questions/**
#routes 2
spring.cloud.gateway.routes[1].id=QuizService
spring.cloud.gateway.routes[1].uri=lb://QUIZSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/quizzes/**


