spring.application.name=QuizService
spring.mongodb.uri=mongodb+srv://njha5901:Jha%402005@cluster0.ya15fxa.mongodb.net/quiz-service?retryWrites=true&w=majority

server.port=8080
eureka.client.enabled=false
