spring.application.name=QuizService
spring.data.mongodb.uri=mongodb+srv://njha5901:Jha%402005@cluster0.ya15fxa.mongodb.net/quiz-service?retryWrites=true&w=majority

server.port=8080

# ENABLE Feign circuit breaker (this was the issue - we need it ON)
spring.cloud.openfeign.circuitbreaker.enabled=false



# ===== Retry Configuration =====
resilience4j.retry.instances.QuestionService.maxAttempts=2
resilience4j.retry.instances.QuestionService.waitDuration=1000
resilience4j.retry.instances.QuestionService.retryExceptions=feign.FeignException

# ===== Circuit Breaker for QuestionService (Feign level) =====
resilience4j.circuitbreaker.instances.QuestionService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.QuestionService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.QuestionService.slidingWindowSize=2
resilience4j.circuitbreaker.instances.QuestionService.minimumNumberOfCalls=1
resilience4j.circuitbreaker.instances.QuestionService.permittedNumberOfCallsInHalfOpenState=1
resilience4j.circuitbreaker.instances.QuestionService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.QuestionService.automaticTransitionFromOpenToHalfOpenEnabled=true

# ===== Circuit Breaker for createQuiz (Service level) =====
resilience4j.circuitbreaker.instances.QuestionServicegetQuestionForQuizStringint.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.QuestionServicegetQuestionForQuizStringint.failureRateThreshold=50
resilience4j.circuitbreaker.instances.QuestionServicegetQuestionForQuizStringint.slidingWindowSize=2
resilience4j.circuitbreaker.instances.QuestionServicegetQuestionForQuizStringint.minimumNumberOfCalls=1
resilience4j.circuitbreaker.instances.QuestionServicegetQuestionForQuizStringint.permittedNumberOfCallsInHalfOpenState=1
resilience4j.circuitbreaker.instances.QuestionServicegetQuestionForQuizStringint.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.QuestionServicegetQuestionForQuizStringint.automaticTransitionFromOpenToHalfOpenEnabled=true

# ===== Circuit Breaker for getQuizById (Service level) =====
resilience4j.circuitbreaker.instances.quizService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.quizService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.quizService.slidingWindowSize=2
resilience4j.circuitbreaker.instances.quizService.minimumNumberOfCalls=1
resilience4j.circuitbreaker.instances.quizService.permittedNumberOfCallsInHalfOpenState=1
resilience4j.circuitbreaker.instances.quizService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.quizService.automaticTransitionFromOpenToHalfOpenEnabled=true

# Logging
logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG