spring.application.name=QuizService
spring.data.mongodb.uri=mongodb+srv://njha5901:Jha%402005@cluster0.ya15fxa.mongodb.net/quiz-service?retryWrites=true&w=majority

server.port=8080




# ===== Retry Configuration =====
resilience4j.retry.instances.QuestionServiceRetry.maxAttempts=3
resilience4j.retry.instances.QuestionServiceRetry.waitDuration=2s
resilience4j.retry.instances.QuestionServiceRetry.retryExceptions=java.lang.Exception


# ===== Circuit Breaker for QuestionService (Feign level) =====
resilience4j.circuitbreaker.instances.QuestionService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.QuestionService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.QuestionService.slidingWindowSize=3
resilience4j.circuitbreaker.instances.QuestionService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.QuestionService.permittedNumberOfCallsInHalfOpenState=1
resilience4j.circuitbreaker.instances.QuestionService.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.QuestionService.automaticTransitionFromOpenToHalfOpenEnabled=true

# ===== Circuit Breaker for GetQuestionService (Feign level) =====
resilience4j.circuitbreaker.instances.GetQuestionService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.GetQuestionService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.GetQuestionService.slidingWindowSize=3
resilience4j.circuitbreaker.instances.GetQuestionService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.GetQuestionService.permittedNumberOfCallsInHalfOpenState=1
resilience4j.circuitbreaker.instances.GetQuestionService.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.GetQuestionService.automaticTransitionFromOpenToHalfOpenEnabled=true

# Circuit Breaker ki priority set karna taaki Retry pehle chale
resilience4j.retry.circuit-breaker-aspect-order=1
resilience4j.circuitbreaker.circuit-breaker-aspect-order=2

# Logging
logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG